version: "3.9"

services:
  todo-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - type: volume
        source: todo-data
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: todo-user
      MYSQL_PASSWORD: todopassword
      MYSQL_DATABASE: todo

volumes:
  todo-data:
